[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q --strict-markers"
testpaths = [
    "agents_test",
]
markers = [
    "agent_test: marks tests as agent validation tests",
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "behavior: marks tests as behavior validation tests",
    "safety: marks tests as safety validation tests",
    "asyncio: marks tests as async tests",
]

[tool.pytest_asyncio]
asyncio_mode = "auto"